# Generated by Django 5.1.5 on 2026-03-08 09:54

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_solicitudamistad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='score_base',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=app.models.profile_picture_path),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_predefinida', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archivo',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='app.categoria'),
        ),
    ]
