# Generated by Django 5.1.5 on 2026-03-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_archivo_score_base_alter_archivo_archivo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='sentimiento',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='score_base',
            field=models.FloatField(default=3),
        ),
    ]
