# Generated by Django 5.1.5 on 2026-03-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_conversacion_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacion',
            old_name='participantes',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversacion',
            new_name='conversation',
        ),
    ]
