# Generated by Django 5.1.5 on 2026-03-27 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_participantes_conversacion_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversacion',
            new_name='Conversation',
        ),
    ]
