# Generated by Django 5.1.5 on 2026-04-07 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_perfil_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_modelo', models.CharField(max_length=100)),
                ('confianza', models.FloatField()),
                ('estado', models.CharField(choices=[('bloqueado', 'Bloqueado - pendiente de revision'), ('confirmaso', 'Confirmado - contenido bloqueado'), ('apelado', 'Apelado - el usuario soicita revision'), ('restaurado', 'Restaurado - falso positivo')], default='bloqueado', max_length=20)),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_revision', models.TextField(blank=True)),
                ('archivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueado', to='app.archivo')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_moderacion', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_bloqueado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenido Bloqueado',
                'verbose_name_plural': 'Contenidos Bloqueados',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
    ]
