# Generated by Django 5.1.5 on 2026-04-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contenidobloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contenidobloqueado',
            name='archivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_bloqueado', to='app.archivo'),
        ),
    ]
